const valueMapping = {
  Yes: { en: "Yes", es: "Sí", fr: "Oui", ar: "نعم" },
  No: { en: "No", es: "No", fr: "Non", ar: "لا" },
  Canada: { en: "Canada", es: "Canadá", fr: "Canada", ar: "كندا" },
  Citizen: { en: "Citizen", es: "Ciudad", fr: "Citoyen", ar: "المواطن" },
  "Permanent resident": { en: "Permanent resident", es: "Residente permanente", fr: "Résident permanent", ar: "المقيم"},
  "Protected Person": { en: "Protected Person", es: "Persona protegida", fr: "Personne protégée", ar: "الشخص المحمي" },
  "Refugee Claimant": { en: "Refugee Claimant", es: "Reclamante de refugiados", fr: "Demandeur d'asile", ar: "Claimant" },
  "Foreign National": { en: "Foreign National", es: "Foreign National", fr: "Étranger", ar: "الجنسية الأجنبية" },
  Other: { en: "Other", es: "Otros", fr: "Autre", ar: "أخرى" },
  Family: { en: "Family", es: "Familia", fr: "Famille", ar: "الأسرة" },
  "TWN (Taiwan)": { en: "TWN (Taiwan)", es: "TWN (Taiwan)", fr: "TWN (Taiwan)", ar: "TWN (Taiwan)" },
  "ISR (Israel)": { en: "ISR (Israel)", es: "ISR (Israel)", fr: "ISR (Israël)", ar: "ISR (Israel)" },
  Both: { en: "Both", es: "Ambos", fr: "Les deux langues", ar: "كلاهما" },
  English: { en: "English", es: "Inglés", fr: "Anglais", ar: "الإنكليزية" },
  French: { en: "French", es: "Francés", fr: "Français", ar: "الفرنسية" },
  Neither: { en: "Neither", es: "Ni tampoco", fr: "Aucune", ar: "لا" },
  "Common-Law": { en: "Common-Law", es: "Common-Law", fr: "Conjoint(e) de fait", ar: "Common-Law" },
  Married: { en: "Married", es: "Casado", fr: "Marié(e)", ar: "متزوج" },
  Visitor: { en: "Visitor", es: "Visitante", fr: "Visiteur", ar: "زائر" },
  Worker: { en: "Worker", es: "Trabajador", fr: "Travailleur", ar: "العامل" },
  Student: { en: "Student", es: "Estudiante", fr: "Étudiant", ar: "طالب" },
  "Annulled Marriage": { en: "Annulled Marriage", es: "Matrimonio anulado", fr: "Mariage annulé", ar: "الزواج الملغي'" },
  Divorced: { en: "Divorced", es: "Divorcio", fr: "Divorcé(e)", ar: "الطلاق" },
  Separated: { en: "Separated", es: "Separados", fr: "Séparé", ar: "منفصلة" },
  Single: { en: "Single", es: "Individual", fr: "Célibataire", ar: "واحدة" },
  Unknown: { en: "Unknown", es: "Desconocida", fr: "Inconnu", ar: "غير معروف" },
  Widowed: { en: "Widowed", es: "Esposo", fr: "Veuf(ve)", ar: "أرمل" },
  Business: { en: "Business", es: "Negocios", fr: "Affaires", ar: "الأعمال" },
  Tourism: { en: "Tourism", es: "Turismo", fr: "Tourisme", ar: "السياحة "},
  Study: { en: "Study", es: "Estudio", fr: "Étudier", ar: "الدراسة" },
  Work: { en: "Work", es: "Trabajo", fr: "Travailler", ar: "العمل" },
  "Family Visit": { en: "Family Visit", es: "Family Visit", fr: "Visite de la famille", ar: "زيارة الأسرة" },
  Economic: { en: "Economic", es: "Económico", fr: "Immigration économique", ar: "Economic" },
  Refugee: { en: "Refugee", es: "Refugiados", fr: "Refugié", ar: "اللاجئون" },
};

export default valueMapping;
