
let questions = {
    welcome: '¡Hola! Soy Luna, y los estaré guiando a través de sus aplicaciones para',
    finish: "Has terminado tu solicitud de",
    // application details
    "¿Programa bajo el cual usted está aplicando?": 34,
    "¿Categoría bajo la cual usted está aplicando?": 24,
    "¿Cuántos miembros de la familia, incluido usted, hay en esta solicitud (consulte la guía de instrucciones)?": 25,
    "¿Preferencia de idioma para la correspondencia?": 26,
    "¿Preferencia de idioma para la entrevista?": 27,
    "Intérprete solicitado?": 28,
    "¿En qué provincia/territorio piensa vivir en Canadá?": 29,
    "¿En qué ciudad/pueblo piensas vivir en Canadá?": 30,
    "¿Ha recibido su Certificat de sélection Québec (CSQ)?": 31,
    "Indique el número de su Certificat de sélection Québec (CSQ)": 32,
    "¿Ha solicitado alguna vez el Certificat de sélection Québec (CSQ)?": 33,

    // personal details
    "¿Cuál es su(s) apellido(s)? (exactamente como se muestra en su pasaporte o documento de viaje)": 1,
    "¿Cuál es su(s) nombre(s) de pila? (exactamente como se muestra en su pasaporte o documento de viaje)": 2,
    "¿Alguna vez ha usado algún otro nombre (por ejemplo, apodo, apellido de soltera, alias, etc.)?": 3,
    "Proporcione los apellidos (por ejemplo, apodo, apellido de soltera, alias, etc.)": 4,
    "Proporcione los nombres (por ejemplo, apodo, apellido de soltera, alias, etc.)": 5,
    "¿Cuál es tu UCI?": 6,
    "¿Cuál es su género?": 7,
    "¿Cuanto mides? Utilice cm como unidad.": 8,
    "¿Cuál es tu color de ojos?": 9,
    "¿Cuándo es tu fecha de nacimiento?": 10,
    "¿Dónde fue su país de nacimiento?": 11,
    "¿Dónde fue su ciudad/pueblo de nacimiento?": 12,
    "¿Cuál es su país de ciudadanía?": 13,
    "¿Tiene más de una ciudadanía?": 105,
    "Por favor, elija su segunda ciudadanía?": 106,
    "¿Dónde está su país de residencia actual?": 14,
    [`¿Cuál es su estado en {14||14.2}?`]: 15,
    [`¿Cuál es el otro estado en {14||14.2}?`]: 273,
    [`¿Cuándo comenzó el {15||15.2||273||273.2} estado en {14||14.2}?`]: 275,
    [`¿Cuándo apareció el {15||15.2||273||273.2} estado finaliza en {14||14.2}?`]: 276,
    "¿Cuándo fue su última entrada a Canadá?": 16,
    "¿Dónde fue su última entrada a Canadá?": 17,
    "Durante los últimos cinco años, ¿ha vivido en algún país que no sea su país de ciudadanía o su actual residencia (indicado anteriormente) durante más de seis meses?": 18,
    "Por favor proporcione detalles. ¿Qué país era?": 19,
    [`¿Cuál era el otro estado en {19||19.2||19.3||19.4}?`]: 272,
    [`¿Cuál era su estado en {19||19.2||19.3||19.4}?`]: 119,
    [`¿Cuándo comenzó el estado de {272||272.2||272.3||272.4||119||119.2||119.3||119.4} en {19||19.2||19.3||19.4}?`]: 133,
    [`¿Cuándo finalizó el estado de {272||272.2||272.3||272.4||119||119.2||119.3||119.4} en {19||19.2||19.3||19.4}?`]: 134,
    [`A excepción de {19||19.2||19.3||19.4}, durante los últimos cinco años, ¿ha vivido en algún país que no sea su país de ciudadanía o su país de residencia actual (indicado arriba) durante más de seis meses?`]: 117,
    "¿Qué país fue su segundo país de residencia anterior?": 20,
    [`¿Cuál era su estado en {20||20.2||20.3||20.4}?`]: 21,
    [`¿Cuál era el otro estado en {20||20.2||20.3||20.4}?`]: 22,
    [`¿Cuándo comenzó el estado de {21||21.2||21.3||21.4||22||22.2||22.3||22.4} en {20||20.2||20.3||20.4}?`]: 210,
    [`¿Cuándo finalizó el estado de {21||21.2||21.3||21.4||22||22.2||22.3||22.4} en {20||20.2||20.3||20.4}?`]: 23,
    "¿Cuál es su estado civil actual?": 86,
    "Proporcione la fecha en que se casó o entró en la relación de hecho.": 95,
    "Proporcione el(los) apellido(s) de su actual cónyuge/pareja de hecho?": 96,
    "Proporcione el(los) nombre(s) de su actual cónyuge/pareja de hecho?": 230,
    "¿Ha estado casado o en una relación de hecho anteriormente?": 231,
    "Proporcione el(los) apellido(s) de su anterior cónyuge/pareja de hecho.": 232,
    "Proporcione el(los) nombre(s) de pila de su anterior cónyuge/pareja de hecho.": 233,
    "¿Cuál era el tipo de su relación anterior?": 90,
    [`¿Cuándo comenzó el estado de {90||90.2||90.3||90.4}??`]: 91,
    [`¿Cuándo finalizó el estado de {90||90.2||90.3||90.4}?`]: 92,
    "¿Cuál fue la fecha de nacimiento de su pareja?": 93,

    // personal details(student, worker)
    "¿Cuál es su estatus en Canadá?": 129,
    [`¿Cuándo comenzó el estado de {129||283||129.1||283.1} en Canadá?`]: 130,
    [`¿Cuándo finalizó el estado de {129||283||129.1||283.1} en Canadá?`]: 131,
    "¿Cuál es el otro estatus en Canadá?": 283,

    // contact information
    "¿Cuál es su apartado de correos? ¿caja?": 35,
    "¿Cuál es su apartamento/unidad?": 36,
    "¿Cuál es el número de la calle?": 37,
    "¿Cuál es el nombre de la calle?": 38,
    "¿Cuál es la ciudad/pueblo?": 39,
    "¿En qué país?": 40,
    "¿Qué es la provincia/estado?": 41,
    "¿Qué es el distrito?": 42,
    "¿Cuál es el código postal?": 43,
    "¿Es su dirección residencial la misma que su dirección postal?": 44,
    "¿Cuál es el apartamento/unidad de su dirección residencial?": 45,
    "¿Cuál es el número de la calle de su dirección residencial?": 46,
    "¿Cuál es el nombre de la calle de su dirección residencial?": 47,
    "¿Cuál es la ciudad/pueblo de su dirección residencial?": 48,
    "¿Cuál es el país de su dirección residencial?": 49,
    "¿Cuál es la provincia/estado de su dirección residencial?": 50,
    "¿Cuál es el distrito de su dirección residencial?": 51,
    "¿Cuál es el código postal de su domicilio?": 52,
    "¿Su número de teléfono pertenece a Canadá/EE.UU.?": 53,
    "¿Su número de teléfono pertenece a otro país?": 277,
    "¿Cuál es el tipo de su número de teléfono?": 54,
    "¿Cuál es el código de país de su número de teléfono?": 55,
    "¿Cuál es tu número de teléfono?": 56,
    "¿Cuál es la ext. de su número de teléfono?": 57,
    "¿Tiene un número de teléfono alternativo?": 148,
    "¿Su número de teléfono alternativo pertenece a Canadá/EE. UU.?": 58,
    "¿Su número de teléfono alternativo pertenece a otro país?": 278,
    "¿Cuál es el tipo de su número de teléfono alternativo?": 59,
    "¿Cuál es el código de país de su número de teléfono alternativo?": 60,
    "¿Cuál es su número de teléfono alternativo?": 61,
    "¿Cuál es la ext. de su número de teléfono alternativo?": 62,
    "¿Su número de fax pertenece a Canadá/EE.UU.?": 63,
    "¿Su número de fax pertenece a otro país?": 279,
    "¿Cuál es el código de país de su número de fax?": 64,
    "¿Cuál es el número de fax?": 65,
    "¿Cuál es la ext. de su número de fax?": 66,
    "¿Cuál es tu dirección de correo electrónico?": 67,

    // passport
    "¿Tiene un pasaporte/documento de viaje válido?": 68,
    "¿Cuál es su número de pasaporte/documento de viaje (exactamente como se muestra en su pasaporte o documento de viaje)?": 69,
    "¿Cuál es el país de emisión de su pasaporte/documento de viaje?": 70,
    "¿Cuándo fue la fecha de emisión de su pasaporte/documento de viaje?": 71,
    "¿Cuándo será la fecha de vencimiento de su pasaporte/documento de viaje?": 72,
    "Para este viaje, ¿utilizará un pasaporte emitido por el Ministerio de Asuntos Exteriores de Taiwán que incluya su número de identificación personal?": 73,
    "Para este viaje, ¿utilizará un pasaporte nacional israelí?": 74,

    // passport(student, worker)
    "¿Cuál es su número de pasaporte?": 140,
    "¿Cuál es el país/territorio de emisión de su pasaporte?": 141,
    "¿Cuándo fue la fecha de emisión de su pasaporte?": 142,
    "¿Cuándo será la fecha de vencimiento de su pasaporte?": 143,

    // national identiry document
    "¿Tienes un documento nacional de identidad?": 75,
    "¿Qué es el número del documento nacional de identidad?": 76,
    "¿Cuál fue el país que emitió su documento nacional de identidad?": 77,
    "¿Cuándo fue la fecha de emisión de su documento nacional de identidad?": 121,
    "¿Cuándo será la fecha de vencimiento de su documento nacional de identidad?": 122,

    // education/occupation detail
    "¿Cual es tu nivel más alto de educación?": 78,
    "¿Cuántos años de educación en total?": 79,
    "¿Cuál es su ocupación actual?": 80,
    "¿Cuál es su ocupación prevista?": 81,

    // language detail
    "¿Cuál es su lengua materna/lengua materna?": 82,
    "¿Es capaz de comunicarse en inglés y/o francés?": 83,
    "¿En qué idioma te sientes más cómodo?": 84,
    "¿Ha realizado un examen de una agencia de evaluación designada para evaluar su competencia en inglés o francés?": 85,

    // dependents personal detail
    "¿También está solicitando un dependiente?": 280,
    "¿Cuál es su relación con el dependiente?": 107,
    "¿Cuál es la otra relación con el dependiente?": 234,
    "¿Acompañará al solicitante principal a Canadá?": 108,
    "¿Cuáles son las razones para no acompañar?": 235,
    "¿Cuál es el tipo dependiente?": 109,
    "Por favor conteste lo siguiente para su dependiente. ¿Cuál es su(s) apellido(s)? (exactamente como se muestra en su pasaporte o documento de viaje)": 290,

    // change of condition detail (student)
    "¿En qué idioma le gustaría ser atendido?": 123,
    "¿Está solicitando un permiso de estudio por primera vez o extiende su permiso de estudio?": 222,
    "¿Está solicitando la restauración de su estatus como estudiante?": 223,
    "¿Está solicitando un nuevo permiso de residencia temporal (solo para solicitantes inadmisibles)?": 224,

    // change of condition detail (worker)
    "¿Está solicitando un permiso de trabajo con el mismo empleador?": 183,
    "¿Está solicitando un permiso de trabajo por primera vez o con un nuevo empleador?": 184,
    "¿Está solicitando el restablecimiento de su condición de trabajador?": 185,

    // US PR card (student, worker)
    "¿Es usted un residente permanente legal de los Estados Unidos con una tarjeta de registro de extranjero válida (tarjeta verde)?": 144,
    "¿Cuál es el número de documento?": 145,
    "¿Cuándo será la fecha de caducidad?": 146,

    // coming into Canada(student, worker)
    "¿Cuándo fue su entrada original a Canadá?": 244,
    "¿Dónde fue su entrada original a Canadá?": 245,
    "¿Cuál es la ciudad/pueblo de su entrada original a Canadá?": 246,
    "¿Cuál era el otro propósito?": 247,
    "¿Fue su entrada más reciente a Canadá la misma que la entrada original?": 248,
    "¿Cuándo fue su ingreso más reciente a Canadá?": 249,
    "¿Dónde fue su entrada más reciente a Canadá?": 250,
    "En su caso, proporcione el número de documento del Registro de Visitantes, Permiso de Estudio, Permiso de Trabajo o Permiso de Residente Temporal más reciente que se le haya emitido.": 251,

    // employment(student, worker)
    "¿Cuándo comenzó su empleo actual?": 156,
    "¿Cuándo termina su empleo actual?": 157,
    "¿Cuál es su actividad/ocupación actual?": 158,
    "¿Cuál es el nombre de la empresa/empleador/instalación?": 159,
    [`¿Cuál es la ciudad/pueblo de {159||159.1||159.2||159.3}?`]: 160,
    [`¿Cuál es el país de {159||159.1||159.2||159.3}?`]: 161,
    ["¿Cuál es la provincia/estado de {159||159.1||159.2||159.3}?"]: 286,
    "¿Tienes más experiencia laboral?": 162,
    "¿Cuándo comenzó su empleo anterior?": 163,
    "¿Cuándo terminó su empleo anterior?": 164,
    "¿Cuál era su actividad/ocupación anterior?": 165,
    "¿Cuál era el nombre anterior de la empresa/empleador/instalación?": 166,
    [`¿Cuál es la ciudad/pueblo de {166||166.1||166.2||166.3}?`]: 167,
    [`¿Cuál era el país de {166||166.1||166.2||166.3}?`]: 168,
    [`¿Cuál era la provincia/estado de {166||166.1||166.2||166.3}?`]: 236,
    "¿Tienes más de dos experiencias laborales?": 281,
    "¿Cuándo comenzó su segundo empleo anterior?": 237,
    "¿Cuándo terminó su segundo empleo anterior?": 238,
    "¿Cuál fue su segunda actividad/ocupación anterior?": 239,
    "¿Cuál era el segundo nombre anterior de la empresa/empleador/instalación?": 240,
    [`¿Cuál es la ciudad/pueblo de {240||240.1||240.2||240.3}?`]: 241,
    [`¿Cuál es el país de {240||240.1||240.2||240.3}?`]: 242,
    [`¿Cuál es la provincia/estado de {240||240.1||240.2||240.3}?`]: 243,

    // background infomaion(student, worker)
    "Debe completar la siguiente sección si tiene 18 años de edad o más. ¿Quieres continuar?": 169,
    "En los últimos dos años, ¿usted o un miembro de su familia ha tenido tuberculosis de los pulmones o ha estado en contacto cercano con una persona con tuberculosis?": 170,
    "¿Tiene algún trastorno físico o mental que requiera servicios sociales y/o de salud, además de medicamentos, durante una estadía en Canadá?": 171,
    "Proporcione detalles si responde SÍ a cualquiera de las dos últimas preguntas.": 172,
    "¿Ha permanecido alguna vez más allá de la validez de su estatus, asistido a la escuela sin autorización o trabajado sin autorización en Canadá?": 173,
    "¿Alguna vez le negaron una visa o un permiso, le negaron la entrada o le ordenaron salir de Canadá o de cualquier otro país o territorio?": 174,
    "¿Ha solicitado previamente ingresar o permanecer en Canadá?": 175,
    "Proporcione detalles si responde SÍ a cualquiera de las últimas tres preguntas.": 176, 
    "¿Alguna vez ha cometido, ha sido arrestado o ha sido acusado o condenado por algún delito penal en cualquier país o territorio?": 177,
    "Proporcione detalles si respondió SÍ a las últimas preguntas.": 178, 
    "¿Prestó servicio en alguna unidad militar, de milicia o de defensa civil o en una organización de seguridad o fuerza policial (incluido el servicio nacional no obligatorio, las unidades de reserva o de voluntarios)?": 179,
    "Proporcione las fechas de servicio y los países o territorios donde prestó servicios.": 180,
    "¿Es usted, o alguna vez ha sido miembro o está asociado con algún partido político u otro grupo u organización que se haya involucrado o defendido la violencia como un medio para lograr un objetivo político o religioso, o que se haya asociado con actividades delictivas en cualquier tiempo?": 181,
    "¿Alguna vez ha presenciado o participado en malos tratos a prisioneros o civiles, saqueos o profanaciones de edificios religiosos?": 182,

    // education(student, worker)
    "¿Ha tenido alguna educación postsecundaria (incluida la universidad, la universidad o la formación de aprendices)?": 149,
    "¿Cuándo comenzó su nivel más alto de educación postsecundaria?": 150,
    "¿Cuándo terminó su nivel más alto de educación postsecundaria?": 151,
    "¿Cuál es el campo y el nivel de estudio?": 152,
    "¿Cuál es el nombre de la escuela/instalación?": 153,
    [`¿Cuál es la ciudad/pueblo de {153||153.1||153.2||153.3}?`]: 154,
    [`¿Cuál es el país o territorio de {153||153.1||153.2||153.3}?`]: 155,
    [`¿Cuál es la provincia/estado de {153||153.1||153.2||153.3}?`]: 282,

    // details of intended study in Canada(student)
    "¿Cómo se llama la escuela en la que te han aceptado?": 252,
    [`¿Qué nivel de estudio será en {252||252.1}?`]: 253,
    [`¿Qué campo de estudio será en {252||252.1}?`]: 254,
    [`¿Cual es la provincia de {252||252.1}?`]: 255,
    [`¿Cuál es la ciudad/pueblo de {252||252.1}?`]: 256,
    [`¿Cuál es la dirección de {252||252.1}?`]: 257,
    "¿Cuál es el número de la institución de aprendizaje designada?": 258,
    "¿Cuál es su número de identificación de estudiante?": 259,
    "¿Cuándo comenzará la duración del estudio esperado?": 260,
    "¿Cuándo terminará la duración del estudio esperado?": 261,
    "¿Cuánto es el costo de la matrícula para sus estudios?": 262,
    "¿Cuánto será el costo de alojamiento y comida de sus estudios?": 263,
    "¿Cuánto será el otro costo de sus estudios?": 264,
    "¿Cuántos fondos hay disponibles para su estadía (CAD)?": 265,
    "Sus gastos en Canadá serán pagados por:": 266,
    "¿Cuál es el otro que pagará tus gastos?": 267,
    "Además de un permiso de estudios, ¿también solicita un permiso de trabajo?": 268,
    "Qué tipo de permiso de trabajo está solicitando:": 269,
    "¿Cuál es su número de Certificado de Aceptación de Quebec (CAQ)?": 270,
    "¿Cuándo será la fecha de vencimiento del Certificado de Aceptación de Quebec (CAQ)?": 271,

    // details of intended work in Canada(worker) 
    "¿Qué tipo de permiso de trabajo está solicitando?": 186,
    "¿Cuál es el otro tipo de permiso de trabajo?": 187,
    "¿Cuál es el nombre de su empleador? (Si está empleado por un empleador extranjero al que se le ha otorgado un contrato para brindar servicios a una entidad canadiense, identifique al empleador extranjero aquí)": 189,
    [`¿Cual es la direccion completa de {189||189.1} (Canadiense o extranjero)?`]: 190,
    [`¿Cual es la provincia de {189||189.1}?`]: 191,
    [`¿Cuál es la ciudad/pueblo de {189||189.1}?`]: 192,
    [`¿Cuál es la dirección de {189||189.1}?`]: 193,
    "¿Cuál será el título del trabajo de su ocupación en Canadá?": 194,
    "Proporcione una breve descripción de las funciones.": 195,
    "¿Cuándo comenzará la duración del empleo esperado?": 196,
    "¿Cuándo terminará la duración del empleo esperado?": 197,
    "¿Qué es el Núm. de Evaluación de Impacto del Mercado Laboral (LMIA) u Oferta de Empleo (Exento de LMIA)?": 198,
    "¿Se le ha emitido un Certificado de Aceptación de Quebec (CAQ)?": 199,
    "¿Se le ha emitido un certificado bajo el programa de Nominación Provincial?": 202,
};
export default questions;



